/*
  @/tmp/oracle/Project9/Project9.sql
*/

/*
Name: Riya Nagpal
ID: 2220097
Date: 2022/11/22
Description - Databases 2 - Project 9
*/

SPOOL /tmp/oracle/Project9/Project9_SPOOL.txt

SELECT    
    to_char(sysdate, 'DD Month YYYY Year Day HH:MI:SS Am') 
FROM dual;

SET SERVEROUTPUT ON

/*
Question 1: des02, script 7clearwater
Create a package with OVERLOADING procedure used to insert a new customer. The user has
the choice of providing either
a/ Last Name, address
b/ Last Name, birthdate
c/ Last Name, First Name, birthdate
d/ Customer id, last name, birthdate
In case no customer id is provided, please use a number from a sequence called
customer_sequence
*/

CONNECT des02/des02

SET SERVEROUTPUT ON

CREATE OR REPLACE PACKAGE NEW_CUSTOMER IS
	PROCEDURE CUST(LASTNAME VARCHAR,ADDRESS VARCHAR);
	PROCEDURE CUST(LASTNAME VARCHAR,BIRTH_DATE DATE);
	PROCEDURE CUST(LASTNAME VARCHAR,FIRSTNAME VARCHAR,BIRTH_DATE DATE);
	PROCEDURE CUST(P_CID NUMBER,LASTNAME VARCHAR,BIRTH_DATE DATE);
END;
/

 CREATE SEQUENCE NEW_CUSTOMER_SEQ START WITH 9 INCREMENT BY 1;

	SELECT NEW_CUSTOMER_SEQ.NEXTVAL FROM DUAL;
	

CREATE OR REPLACE PACKAGE BODY NEW_CUSTOMER IS
	PROCEDURE CUST(LASTNAME VARCHAR,ADDRESS VARCHAR)
	AS
	BEGIN	
		INSERT INTO CUSTOMER
		VALUES (NEW_CUSTOMER_SEQ.NEXTVAL,LASTNAME,'','','',ADDRESS,'','','','','','','');
		
		DBMS_OUTPUT.PUT_LINE('DATA SUCCESFULLY ADDED INTO THE TABLE');
		
		COMMIT;
	END CUST;
	
	PROCEDURE CUST(LASTNAME VARCHAR,BIRTH_DATE DATE)
	AS
	BEGIN	
		INSERT INTO CUSTOMER
		VALUES (NEW_CUSTOMER_SEQ.NEXTVAL,LASTNAME,'','',BIRTH_DATE,'','','','','','','','');
	END CUST;
	
	PROCEDURE CUST(LASTNAME VARCHAR,FIRSTNAME VARCHAR,BIRTH_DATE DATE)
	AS
	BEGIN	
		INSERT INTO CUSTOMER
		VALUES (NEW_CUSTOMER_SEQ.NEXTVAL,LASTNAME,FIRSTNAME,'',BIRTH_DATE,'','','','','','','','');
		
		DBMS_OUTPUT.PUT_LINE('DATA SUCCESFULLY ADDED INTO THE TABLE');
		COMMIT;
	END CUST;
	
	PROCEDURE CUST(P_CID NUMBER,LASTNAME VARCHAR,BIRTH_DATE DATE)
	AS
		TEMP_CID CUSTOMER.C_ID%TYPE;
	BEGIN	
		SELECT C_ID
		INTO TEMP_CID
		FROM CUSTOMER
		WHERE C_ID=P_CID;
		DBMS_OUTPUT.PUT_LINE('CUSTOMER ID IS ALREADY EXIST IN THE TABLE');
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
				INSERT INTO CUSTOMER
				VALUES (P_CID,LASTNAME,'','','',BIRTH_DATE,'','','','','','','');
				DBMS_OUTPUT.PUT_LINE('DATA SUCCESFULLY ADDED INTO THE TABLE');
				COMMIT;
	END CUST;
END;
/

BEGIN
	NEW_CUSTOMER.CUST('RYAN',TO_DATE('05/11/200', 'MM/DD/YYYY'));
END;
/

BEGIN
	NEW_CUSTOMER.CUST('BEN','AFFLECK',TO_DATE('01/07/2001', 'MM/DD/YYYY'));
END;
/

BEGIN
	NEW_CUSTOMER.CUST(13,'NEIL',TO_DATE('02/02/2006', 'MM/DD/YYYY'));
END;
/

/*
Question 2: des03, script 7northwoods
Create a package with OVERLOADING procedure used to insert a new student. The user has the
choice of providing either
a/ Student id, last name, birthdate
b/ Last Name, birthdate
c/ Last Name, address
d/ Last Name, First Name, birthdate, faculty id
In case no student id is provided, please use a number from a sequence called
student_sequence.
Make sure that the package with the overloading procedure is user friendly enough to handle
error such as:
- Faculty id does not exist
- Student id provided already existed
- Birthdate is in the future
*/

CONNECT des03/des03

SET SERVEROUTPUT ON

CREATE OR REPLACE PACKAGE NEW_STUD IS
	PROCEDURE STUD(STUD_ID NUMBER,LASTNAME VARCHAR2,BIRTH_DATE DATE);
	PROCEDURE STUD(LASTNAME VARCHAR2,BIRTH_DATE DATE);
	PROCEDURE STUD(LASTNAME VARCHAR2,ADDRESS VARCHAR2);
	PROCEDURE STUD(LASTNAME VARCHAR2,FIRSTNAME VARCHAR2, BIRTH_DATE DATE,FACULTYID NUMBER);
END;
/

--PROVIDING SEQUENCE TO THE PACKAGE
 CREATE SEQUENCE STUDENT_SEQUENCE START WITH 7 INCREMENT BY 1;


--FIRST CHECK THE SEQUENCE
	SELECT STUDENT_SEQUENCE.NEXTVAL FROM DUAL;
	

SELECT FLOOR(DBMS_RANDOM.VALUE(1,9)) OUTPUT FROM DUAL;

CREATE OR REPLACE PACKAGE BODY NEW_STUD IS

	--PROCEDURE 1
	PROCEDURE STUD(STUD_ID NUMBER,LASTNAME VARCHAR2,BIRTH_DATE DATE)
	AS
		TEMPSTUDENTID STUDENT.S_ID%TYPE;
	BEGIN

		IF(BIRTH_DATE>SYSDATE)THEN
			DBMS_OUTPUT.PUT_LINE('THE BIRTH DATE IS IN THE FUTURE');
		ELSE
			SELECT S_ID
			INTO TEMPSTUDENTID
			FROM STUDENT
			WHERE S_ID=STUD_ID;
		END IF;
		
		DBMS_OUTPUT.PUT_LINE('THE DATA ALREADY EXISTS IN THE TABLE ');

	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			INSERT INTO STUDENT
			VALUES (STUD_ID,LASTNAME,'','','','','','','','',BIRTH_DATE,'',FLOOR(DBMS_RANDOM.VALUE(1,6)),'');
			
		COMMIT;
	END STUD;
	
	--PROCEDURE 2
	PROCEDURE STUD(LASTNAME VARCHAR2,BIRTH_DATE DATE)
	AS
	BEGIN
		IF(BIRTH_DATE>SYSDATE)THEN
			DBMS_OUTPUT.PUT_LINE('THE BIRTH DATE IS IN THE FUTURE');
		ELSE
			INSERT INTO STUDENT
			VALUES (STUDENT_SEQUENCE.NEXTVAL,LASTNAME,'','','','','','','','',BIRTH_DATE,'',FLOOR(DBMS_RANDOM.VALUE(1,6)),'');
		END IF;
		COMMIT;
	END STUD;
	
	--PROCEDURE 3
	PROCEDURE STUD(LASTNAME VARCHAR2,ADDRESS VARCHAR2)
	AS
	BEGIN
		INSERT INTO STUDENT
		VALUES (STUDENT_SEQUENCE.NEXTVAL,LASTNAME,'','',ADDRESS,'','','','','','','',FLOOR(DBMS_RANDOM.VALUE(1,6)),'');
		COMMIT;
	END STUD;
	
	--PROCEDURE 4
	PROCEDURE STUD(LASTNAME VARCHAR2,FIRSTNAME VARCHAR2, BIRTH_DATE DATE,FACULTYID NUMBER)
	AS
		TEMPFACID FACULTY.F_ID%TYPE;
	BEGIN
		IF(BIRTH_DATE>SYSDATE)THEN
			DBMS_OUTPUT.PUT_LINE('THE BIRTH DATE IS IN THE FUTURE');
		ELSE
			SELECT F_ID
			INTO TEMPFACID
			FROM FACULTY
			WHERE F_ID=FACULTYID;
			
			INSERT INTO STUDENT
			VALUES (STUDENT_SEQUENCE.NEXTVAL,LASTNAME,FIRSTNAME,'','','','','','','',BIRTH_DATE,'',FACULTYID,'');
			
		END IF;
		
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			DBMS_OUTPUT.PUT_LINE('THE FACULTY ID DOES NOT EXIST IN THE PARENT TABLE');
		COMMIT;
	END STUD;
END;
/


BEGIN
	NEW_STUD.STUD(9,'ISHA',TO_DATE('14/05/2004','DD/MM/YYYY'));
END;
/

BEGIN
	NEW_STUD.STUD('RIYA',TO_DATE('28/07/1998','DD/MM/YYYY'));
END;
/

BEGIN
	NEW_STUD.STUD('RYAN','REYNOLDS');
END;
/

BEGIN
	NEW_STUD.STUD('LIVELY','BLAKE',TO_DATE('13/04/2004','DD/MM/YYYY'),20);
END;
/